services:
  postgres:
    image: postgres:bookworm
    container_name: postgres
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: phenom
      POSTGRES_PASSWORD: JSX@2004
    volumes:
      - ${HOME}/docker-volumes/postgres/data:/var/lib/postgresql
      - ${HOME}/docker-volumes/postgres/dump:/db
    ports:
    - "5432:5432"
    networks:
    - db

  dev_pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jadaunabhaysingh220@gmail.com
      PGADMIN_DEFAULT_PASSWORD: jadaun
    ports:
    - "90:80"
    networks:
    - db

networks:
  db:
    name: postgres_db
