services:
  dev_postgres:
    image: postgres:trixie
    container_name: phenom_postgres
    env_file:
    - .env
    volumes:
    - ./.data/postgres:/db
    ports:
    - "5432:5432"

  dev_pgadmin:
    image: dpage/pgadmin4
    container_name: phenom_pgadmin
    env_file:
    - .env
    ports:
    - "90:80"
